title: Ruofan Ma
email: ruofan_ma@g.harvard.edu
description: "PhD Candidate · International Organization · Political Methodology"
github_username: ruofan-ma
show_downloads: true
theme: jekyll-theme-cayman

gems:
  - jekyll-mentions
